-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 23:40:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SIGE5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIGE5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIGE5` DEFAULT CHARACTER SET utf8 ;
USE `SIGE5` ;

-- -----------------------------------------------------
-- Table `SIGE5`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGE5`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nom_empleado` VARCHAR(45) NOT NULL,
  `ape_empleado` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGE5`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGE5`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nom_empresa` VARCHAR(45) NOT NULL,
  `per_contacto` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGE5`.`tipo_licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGE5`.`tipo_licencia` (
  `idtipo_licencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_licencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGE5`.`Licencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGE5`.`Licencias` (
  `idLicencias` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `tipo_licencia_idtipo_licencia` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idLicencias`, `tipo_licencia_idtipo_licencia`),
  INDEX `fk_Licencias_tipo_licencia1_idx` (`tipo_licencia_idtipo_licencia` ASC),
  INDEX `fk_Licencias_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Licencias_tipo_licencia1`
    FOREIGN KEY (`tipo_licencia_idtipo_licencia`)
    REFERENCES `SIGE5`.`tipo_licencia` (`idtipo_licencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Licencias_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `SIGE5`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
